import { ReactNode, useContext, useEffect } from 'react';
import { AppContext } from '@/custom/app-context';
import { useRouter } from 'next/router';
import Head from 'next/head';

export default function UnauthenticatedPageLayout({ children }: { children?: ReactNode }) {
    const appContext = useContext(AppContext);
    const router = useRouter();

    useEffect(() => {
        if (appContext.data.isAuthenticated) {
            router.push('/home');
        }
    }, [appContext.data.isAuthenticated, router])

    if (appContext.data.isAuthenticated) {
        return (
            <></>
        )
    }

    return (
        <>
            <Head>
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <nav className="navbar navbar-expand-md navbar-dark fixed-top bg-dark text-white" style={{ minHeight: 86, maxHeight: 86, overflow: 'hidden' }}>
                    <div className="container-fluid">
                        <div className="d-flex justify-content-start align-items-center w-100">
                            <a className="navbar-brand" href="#">
                                <img src="ofsc.png" alt="Logo" width="60" height="60" />
                            </a>

                            <div>
                                <h5 className="mb-0">Ontario Federation of Snowmobile Clubs</h5>
                            </div>
                        </div>
                    </div>
                </nav>
            </header>

            <main className="flex-shrink-0">
                <div className="container-fluid container-lg flex-shrink-0 py-2">
                    {children}
                </div>
            </main>

            <footer className="footer bg-secondary mt-auto py-2">
                <div className="container-fluid" style={{ padding: 0 }}>
                    <div className="text-white text-center">Need help? Contact OFSC at 705-739-7669 or permits@ofsc.on.ca</div>
                    <div className="text-white text-center">
                        <a href="https://www.facebook.com/pages/The-Ontario-Federation-of-Snowmobile-Clubs-OFSC/125178027502192"><i className="fa-brands fa-facebook-f text-white"></i></a>
                        <a href="https://twitter.com/GoSnowmobiling"><i className="fa-brands fa-twitter ms-4 text-white"></i></a>
                        <a href="https://www.instagram.com/gosnowmobilingontario"><i className="fa-brands fa-instagram ms-4 text-white"></i></a>
                        <a href="https://www.linkedin.com/company/ontario-federation-of-snowmobile-clubs"><i className="fa-brands fa-linkedin-in ms-4 text-white"></i></a>
                        <a href="https://www.youtube.com/user/GoSnowmobiling/videos"><i className="fa-brands fa-youtube ms-4 text-white"></i></a>
                        {/* <span className="d-sm-none">XS</span>
                        <span className="d-none d-sm-block d-md-none">SM</span>
                        <span className="d-none d-md-block d-lg-none">MD</span>
                        <span className="d-none d-lg-block d-xl-none">LG</span>
                        <span className="d-none d-xl-block d-xxl-none">XL</span> */}
                    </div>
                </div>
            </footer>
        </>
    )
}
